EM/THERMAL: Hardcode TjMax for VLV CPU DTS
BZ: 100440

This patch hard codes the TjMax for VLV CPU DTS,
as 90 C. This is required to make CPU DTS report
correct temperature values, until the fix comes
in B0 stepping.

Also, fix a compilation error, for
unused symbol 'core_threshold_work' when
CONFIG_SENSORS_CORETEMP_INTERRUPT is not enabled.

Change-Id: Ieb88d4f1e0376046bf29425f8187750c124d5175
Signed-off-by: Durgadoss R <durgadoss.r@intel.com>
Reviewed-on: http://android.intel.com:8080/101984
Reviewed-by: cactus <cactus@intel.com>
Reviewed-by: Tc, Jenny <jenny.tc@intel.com>
Tested-by: Kallappa Manjanna, MadhukumarX <madhukumarx.kallappa.manjanna@intel.com>
Reviewed-by: buildbot <buildbot@intel.com>
Tested-by: buildbot <buildbot@intel.com>