drm/i915: cover "vxd_release" with CONFIG_DRM_VXD_BYT
BZ:125232

Current code will give compilation error if CONFIG_DRM_VXD_BYT is not defined and CONFIG_PM_RUNTIME is defined. This patch fixes it.

Change-Id: Ib03b7c56684c3b4ab69d758decc3861d28ac93f2
Signed-off-by: naresh kumar kachhi <naresh.kumar.kachhi@intel.com>
Reviewed-on: http://android.intel.com:8080/120021
Reviewed-by: S, Deepak <deepak.s@intel.com>
Reviewed-by: Satyanantha, Rama Gopal M <rama.gopal.m.satyanantha@intel.com>
Reviewed-by: Kumar, Shobhit <shobhit.kumar@intel.com>
Reviewed-by: Smith, Geoff <geoff.smith@intel.com>
Reviewed-by: Cohen, David A <david.a.cohen@intel.com>
Tested-by: Stimson, Dale B <dale.b.stimson@intel.com>
Reviewed-by: buildbot <buildbot@intel.com>
Tested-by: buildbot <buildbot@intel.com>