spi: Fix comparison of different integer types
BZ: 110586

Fix problem discovered with sparse:
+ drivers/spi/spi.c:1554:37: sparse: incompatible types in comparison expression (different signedness)
drivers/spi/spi.c: In function 'spi_write_then_read':
drivers/spi/spi.c:1554:23: warning: comparison of distinct pointer types lacks a cast [enabled by default]

The change to SPI_BUFSIZ was introduced in commit b3a223ee2, "spi:
Remove SPI_BUFSIZ restriction on spi_write_then_read()"

Change-Id: I20ba6a1cf5634e2b4329b966500165f71f439696
Cc: Mark Brown <broonie@opensource.wolfsonmicro.com>
Reported-by: kbuild test robot <fengguang.wu@intel.com>
Signed-off-by: Grant Likely <grant.likely@secretlab.ca>
Signed-off-by: Matt Ranostay <matt.ranostay@intel.com>
Reviewed-on: http://android.intel.com:8080/109375
Reviewed-by: Griffiths, Richard A <richard.a.griffiths@intel.com>
Reviewed-by: Smith, Geoff <geoff.smith@intel.com>
Tested-by: Ng, Cheon-woei <cheon-woei.ng@intel.com>
Reviewed-by: buildbot <buildbot@intel.com>
Tested-by: buildbot <buildbot@intel.com>